services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432
    networks:
      - app_net

  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django_web
    volumes:
     - ./app:/app
     - static_volume:/app/SM_project/static
    env_file:
      - .env
    ports:
      - 8000
    depends_on:
      - db
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - app_net

volumes:
  static_volume:
  postgres_data:

networks:
  app_net:
    driver: bridge